EXTRA_OECMAKE_append_olympus-nuvoton= " -DSEL_LOGGER_MONITOR_THRESHOLD_EVENTS=ON"
EXTRA_OECMAKE_append_olympus-nuvoton= " -DSEL_LOGGER_MONITOR_THRESHOLD_ALARM_EVENTS=ON"
EXTRA_OECMAKE_append_olympus-nuvoton= " -DSEL_LOGGER_MONITOR_WATCHDOG_EVENTS=ON"
EXTRA_OECMAKE_append_olympus-nuvoton= " -DREDFISH_LOG_MONITOR_PULSE_EVENTS=ON"
